### ISSUE TITLE
Fichier AIRR pour les repertoires simulé

### ISSUE THREAD

**Issue by julibinho** [julibinho/repDiversity#1]
Salut @NikaAb, les étudiants sont en train de comparer plusieurs outils d'analyse de diversité, certains nécessitent  d'un fichier en format AIRR, est-que tu peux passer les répertoires qui se trouve à data/repertoires/simulations/ à IMGT et produire ces fichiers.

Merci beaucoup

**Comment by NikaAb** [comment]
Done!
