### ISSUE TITLE
Question about the "germline gene usage" in the report 

### ISSUE THREAD

**Issue by NikaAb** [julibinho/repDiversity#2]
Hi @aluxsn, @DradjatKevin !
You have done a great job so far :) 
I was looking at your report here : [https://github.com/julibinho/repDiversity/blob/main/documments/repports/Outils_projet.pdf](url)
In the ImmuneRef section, you have mentioned : "_Nombre de gènes de lignée germinale dans chaque répertoire. Les gènes de lignée germinale (germline genes) sont défins dans la base de donnée International ImMunoGeneTics._" 

I wonder if this is a good translation for "**germline gene usage**". Since it can also be an unclear concept for you, would you please write down in **5 sentences at max**, explaining your understanding about the "germline gene usage"  in this context? It would be great if you say what are germline genes and why they can be used as a source of information for describing a repertoire. 

Thanks !

**Comment by DradjatKevin** [comment]
Hello @NikaAb, 
from what i understood, germline gene usage is the frequency of V, D and J genes used in the VDJ recombination to form the B cell receptor. By calculating these frequencies, we can compare them to a normal frequencies distribution to determine if the repertoire belong to an ill person or not.  We can also observe the evolution of the germline gene usage of a unique repertoire to study the impact of a vaccine per example. Did i misunderstood the concept ?
I think the terms i chose for the translation are not suitable, i will modify this description on the next report.

**Comment by NikaAb** [comment]
Bravo @DradjatKevin ! It's great ! 
I know the names are sometimes confusing so we have "Germline" which translates to "lignée germinale" in french : 

La lignée germinale est l'ensemble des cellules allant des [cellules souches](https://fr.wikipedia.org/wiki/Cellules_souches) aux [gamètes](https://fr.wikipedia.org/wiki/Gam%C3%A8te). On parle également des [cellules germinales](https://fr.wikipedia.org/wiki/Cellules_germinales) qui, contrairement aux [cellules somatiques](https://fr.wikipedia.org/wiki/Cellules_somatiques), transmettent à leur descendance (au cours de la [reproduction sexuée](https://fr.wikipedia.org/wiki/Reproduction_sexu%C3%A9e)) les mutations génétiques qu'elles auraient subies.

Here is what we can say about the Ig's genes : 

Pour chacune de ces chaînes il existe plusieurs gènes V, plusieurs gènes J, plusieurs gènes D et plusieurs gènes C. Au niveau des précurseurs de la lignée B, ces gènes sont en **configuration germinale**, autrement dit ces gènes sont non fonctionnels étant éloignés les uns des autres sur les chromosomes.
![Capture d’écran de 2022-02-25 10-39-12](https://user-images.githubusercontent.com/22688572/155692259-e5524803-6d47-4682-be73-b7ea3ab076c9.png)


And that's all! 


Thanks :)
